"""Cluster config for 2019_changnyeong — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import kma_cluster


CONFIG = kma_cluster(
    name="2019_changnyeong",
    region="2019_changnyeong",
    src_root=os.path.join(config.PROJECT_ROOT, "2019_changnyeong_cluster"),
    epicenter=(35.416, 128.489),
    region_bounds=(35.2, 35.62, 128.28, 128.7),
    station_masters=("KS_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
