"""Cluster config for 2020_haenam — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import stp_cluster


CONFIG = stp_cluster(
    name="2020_Haenam",
    region="2020_haenam",
    src_root=os.path.join(config.PROJECT_ROOT, "2020_haenam_cluster"),
    epicenter=(34.66, 126.401),
    region_bounds=(34.46, 34.87, 126.2, 126.61),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")

# Baked-in mainshock treatment (one-pass; matches the Haenam_joint convention exactly,
# so the joint run's 2020-2020 pair files can be reused verbatim via xcorr resume).
CONFIG = replace(CONFIG, mainshock_event_id="20200503130714", num_cores=24,
                 xcorr_pair_overrides={
    frozenset({"20200503130714"}):     # M3.1  2020-05-03 22:07:14 KST
        dict(pre=0.05, post=0.05, bandpass=(1, 40)),
})
