"""Cluster config for 2024_kimcheon — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import mixed_cluster


CONFIG = mixed_cluster(
    name="2024_kimcheon",
    region="2024_kimcheon",
    src_root=os.path.join(config.PROJECT_ROOT, "2024_kimcheon_cluster"),
    epicenter=(36.231, 128.197),
    region_bounds=(36.03, 36.44, 127.99, 128.4),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
