"""Cluster config for Changnyeong — auto-generated by PocketQuake, then tuned for the
Gwangyang-style **mainshock treatment**: the M2.6 mainshock has a well-determined grade-A
focal mechanism (strike ~10°/dip ~84°/rake ~−168°, near-vertical strike-slip), but the
default dt.cc cloud (3 events stacked within ~30 m) doesn't show a fault plane that matches.
Long correlation windows and a 5–20 Hz band let the mainshock's longer source duration
dominate the alignment of the smaller aftershocks; following Gwangyang we override that pair
with a tighter window (±0.05 s) and a broader band (1–40 Hz)."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import kma_cluster

_MAINSHOCK = "20240912144719"   # UTC: 2024-09-12 14:47:19 — M2.6 (KST 23:47:19)

CONFIG = kma_cluster(
    name="changnyeong",
    region="Changnyeong",
    src_root=os.path.join(config.PROJECT_ROOT, "Changnyeong_cluster"),
    epicenter=(35.463, 128.427),
    region_bounds=(35.3, 35.65, 128.25, 128.65),
    station_masters=("KS_station.csv",),
    dtct_isolv=1,
    mainshock_event_id=_MAINSHOCK,   # also enables the `no_main` dt.cc variant
)

# Gwangyang-style mainshock-pair xcorr override (the factory has no kwarg for this).
CONFIG = replace(
    CONFIG,
    xcorr_pair_overrides={
        frozenset({_MAINSHOCK}): dict(pre=0.05, post=0.05, bandpass=(1, 40)),
    },
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
