"""Cluster config for Chungju — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import kma_cluster


CONFIG = kma_cluster(
    name="chungju",
    region="Chungju",
    src_root=os.path.join(config.PROJECT_ROOT, "Chungju_cluster"),
    epicenter=(37.14, 127.76),
    region_bounds=(36.94, 37.34, 127.56, 127.96),
    station_masters=("KS_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
