"""Cluster config for f1144_b515_reuse — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import stp_cluster


CONFIG = stp_cluster(
    name="f1144_b515_reuse",
    region="f1144_b515_reuse",
    src_root=os.path.join(config.PROJECT_ROOT, "f1144_b515_reuse_cluster"),
    epicenter=(35.7675, 129.3787),
    region_bounds=(35.716, 35.82, 129.325, 129.433),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
