"""Cluster config for Gwangyang_stp — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import stp_cluster


CONFIG = stp_cluster(
    name="gwangyang_stp",
    region="Gwangyang_stp",
    src_root=os.path.join(config.PROJECT_ROOT, "Gwangyang_stp_cluster"),
    epicenter=(35.001, 127.722),
    region_bounds=(34.79, 35.21, 127.51, 127.93),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
