"""Cluster config for Jangsu — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import mixed_cluster


CONFIG = mixed_cluster(
    name="jangsu",
    region="Jangsu",
    src_root=os.path.join(config.PROJECT_ROOT, "Jangsu_cluster"),
    epicenter=(35.645, 127.476),
    region_bounds=(35.44, 35.85, 127.27, 127.68),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
