"""Cluster config for Muan — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import mixed_cluster


CONFIG = mixed_cluster(
    name="muan",
    region="Muan",
    src_root=os.path.join(config.PROJECT_ROOT, "Muan_cluster"),
    epicenter=(34.953, 126.453),
    region_bounds=(34.75, 35.16, 126.25, 126.66),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
