"""Cluster config for Sangju — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import stp_cluster


CONFIG = stp_cluster(
    name="sangju",
    region="Sangju",
    src_root=os.path.join(config.PROJECT_ROOT, "Sangju_cluster"),
    epicenter=(36.502, 128.1),
    region_bounds=(36.3, 36.71, 127.89, 128.31),
    station_masters=("KS_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
CONFIG = replace(CONFIG, phs_weight_scheme="probability")

# Gwangyang-style mainshock treatment for the 2019-07-21 M3.9.
# Narrows the xcorr window for pairs involving the mainshock (its longer source duration
# would otherwise dominate the alignment of the smaller aftershocks at the default
# ±0.5 s / 5-20 Hz window).
from dataclasses import replace as _replace
_MS = "20190721020418"
CONFIG = _replace(CONFIG, mainshock_event_id=_MS,
                  xcorr_pair_overrides={
                      frozenset({_MS}): dict(pre=0.05, post=0.05, bandpass=(1, 40)),
                  })
