"""Cluster config for uf_2013_qc — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import stp_cluster


CONFIG = stp_cluster(
    name="uf_2013_qc",
    region="uf_2013_qc",
    src_root=os.path.join(config.PROJECT_ROOT, "uf_2013_qc_cluster"),
    epicenter=(35.7539, 129.3804),
    region_bounds=(35.551, 35.949, 129.2, 129.599),
    station_masters=("KS_station.csv", "KG_station.csv", "GJ_station.csv",),
    dtct_isolv=2,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")

# ufpipe xcorr overrides (appended by scaffold --xcorr; do not edit by hand)
CONFIG = replace(CONFIG, xcorr=dict(CONFIG.xcorr, interp_hz=1000, cc_threshold=0.7, pre=0.5, post=0.5, margin=0.5, bandpass=(5.0, 20.0)))
