"""Cluster config for uf_subregion_reuse — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import stp_cluster


CONFIG = stp_cluster(
    name="uf_subregion_reuse",
    region="uf_subregion_reuse",
    src_root=os.path.join(config.PROJECT_ROOT, "uf_subregion_reuse_cluster"),
    epicenter=(35.7539, 129.3804),
    region_bounds=(35.551, 35.949, 129.2, 129.599),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
