"""Cluster config for West_jeju — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import mixed_cluster


CONFIG = mixed_cluster(
    name="west_jeju",
    region="West_jeju",
    src_root=os.path.join(config.PROJECT_ROOT, "West_jeju_cluster"),
    epicenter=(33.28, 126.212),
    region_bounds=(33.07, 33.49, 126.0, 126.43),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability", loc_backend="hyposvi", reloc_backend="relocdd_py")
