"""Cluster config for West_gyeongju — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import kma_cluster


CONFIG = kma_cluster(
    name="west_gyeongju",
    region="West_gyeongju",
    src_root=os.path.join(config.PROJECT_ROOT, "West_gyeongju_cluster"),
    epicenter=(35.77, 129.067),
    region_bounds=(35.57, 35.97, 128.86, 129.27),
    station_masters=("KS_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
