"""Cluster config for Yeongyang — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import mixed_cluster


CONFIG = mixed_cluster(
    name="yeongyang",
    region="Yeongyang",
    src_root=os.path.join(config.PROJECT_ROOT, "Yeongyang_cluster"),
    epicenter=(36.767, 129.036),
    region_bounds=(36.56, 36.97, 128.83, 129.24),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
