"""Cluster config for Yeongyang23 — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import mixed_cluster


CONFIG = mixed_cluster(
    name="yeongyang23",
    region="Yeongyang23",
    src_root=os.path.join(config.PROJECT_ROOT, "Yeongyang23_cluster"),
    epicenter=(36.601, 129.076),
    region_bounds=(36.39, 36.81, 128.87, 129.29),
    station_masters=("KS_station.csv", "KG_station.csv",),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability", loc_backend="hyposvi", reloc_backend="relocdd_py")
