"""Cluster config for Yeoncheon — auto-generated by PocketQuake."""
from dataclasses import replace
import os

from pipeline import config
from pipeline.clusters._base import stp_cluster


CONFIG = stp_cluster(
    name="yeoncheon",
    region="Yeoncheon",
    src_root=os.path.join(config.PROJECT_ROOT, "Yeoncheon_cluster"),
    epicenter=(38.122, 127.092),
    region_bounds=(37.79, 38.34, 126.72, 127.33),
    station_masters=("KS_station.csv", "KG_station.csv"),
    dtct_isolv=1,
)

# AI-pick-probability HypoInverse weighting (PocketQuake v1.0.0+ default).
# Set the .phs weight code (column 18) from the PhaseNet+ pick probability instead of
# epicentral-distance bins -- the picker's own confidence is a more direct measure of
# pick quality than distance. To revert to the source-cluster behavior, change to
# `phs_weight_scheme="distance"`.
CONFIG = replace(CONFIG, phs_weight_scheme="probability")
